name: Kyle Daigle
highlighter: pygments
markdown: kramdown
site: Kyle Daigle
description: "Articles about development, people, software, and products written by Kyle Daigle."
url: "http://kyledaigle.com"
